apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-backup-pv-cloudintel
  # labels: 
  #   app: cb
  #   resource: db
  #   env: prod
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare/cb/backup/db
    server: 192.168.3.239
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc-cloudintel
  namespace: cloudintel
  # labels: 
  #   app: cb
  #   resource: db
  #   env: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Gi
  # selector: 
  #   matchLabels:
  #     app: cb
  #     resource: db
  #     env: dev
  apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-backup-pv-cloudintel
  # labels: 
  #   app: cb
  #   resource: db
  #   env: prod
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare/cb/backup/db
    server: 192.168.3.239
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc-cloudintel
  namespace: cloudintel
  # labels: 
  #   app: cb
  #   resource: db
  #   env: prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 50Gi
       