
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudintel-db-claim
  namespace: cloudintel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: alicloud-nas
  volumeMode: Filesystem
