---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudintel-app-config
  namespace: cloudintel
  labels:
    env: prod
data:
  nodeURL: http://47.91.11.214:30202/api/v1/


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudintel-node-config
  namespace: cloudintel
  labels:
    env: prod
data:
  DB_User: root
  DB_Host: cloudintel-db
  DB_Name: cloudintel_db
  DB_Password: smartvm
  DB_Port: "5432"
  PORT: "8080"
  PRICING_DB_User: root
  PRICING_DB_Host: 114.143.207.110
  PRICING_DB_Name: cb_pricing
  PRICING_DB_Password: smartvm
  PRICING_DB_Port: "30535"
  START_SCHEMA_SCHEDULAR: "true"
  PYTHON_API: http://172.24.89.68:30203
  Sender_email: cloudbrain-support@click2cloud.net
  Sender_Password: Click@Cloud!453
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudintel-db-configs
  namespace: cloudintel
  labels:
    env: prod
data:
  postgresql.conf: |
    #------------------------------------------------------------------------------
    # CONNECTIONS AND AUTHENTICATION
    #------------------------------------------------------------------------------

    listen_addresses = '*'
    max_connections = 10000
    tcp_keepalives_count = 9
    tcp_keepalives_idle = 3
    tcp_keepalives_interval = 75

    #------------------------------------------------------------------------------
    # RESOURCE USAGE (except WAL)
    #------------------------------------------------------------------------------

    #shared_preload_libraries = 'pglogical,repmgr'
    max_worker_processes = 10
    shared_buffers = 1GB

    #------------------------------------------------------------------------------
    # WRITE AHEAD LOG
    #------------------------------------------------------------------------------

    wal_level = 'logical'
    wal_log_hints = on
    wal_buffers = 16MB
    checkpoint_completion_target = 0.9

    #------------------------------------------------------------------------------
    # REPLICATION
    #------------------------------------------------------------------------------

    max_wal_senders = 10
    wal_sender_timeout = 0
    max_replication_slots = 10
    hot_standby = on

    #------------------------------------------------------------------------------
    # ERROR REPORTING AND LOGGING
    #------------------------------------------------------------------------------

    log_filename = 'postgresql.log'
    log_rotation_age = 0
    log_min_duration_statement = 5000
    log_connections = on
    log_disconnections = on
    log_line_prefix = '%t:%r:%c:%u@%d:[%p]:'
    log_lock_waits = on

    #------------------------------------------------------------------------------
    # AUTOVACUUM PARAMETERS
    #------------------------------------------------------------------------------

    log_autovacuum_min_duration = 0
    autovacuum_naptime = 5min
    autovacuum_vacuum_threshold = 500
    autovacuum_analyze_threshold = 500
    autovacuum_vacuum_scale_factor = 0.05

    #------------------------------------------------------------------------------
    # LOCK MANAGEMENT
    #------------------------------------------------------------------------------

    deadlock_timeout = 5s

    #------------------------------------------------------------------------------
    # VERSION/PLATFORM COMPATIBILITY
    #------------------------------------------------------------------------------

    escape_string_warning = off
    standard_conforming_strings = on