apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS50aGVjbG91ZHNicmFpbi5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiU0IwRjN0Szc1SzVzIiwiYXV0aCI6IllXUnRhVzQ2VTBJd1JqTjBTemMxU3pWeiJ9fX0=
kind: Secret
metadata:
  name: c2c-regcred
  namespace: cloudintel
  labels:
    env: prod
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: db-conn-secrets
  namespace: cloudintel
  labels:
    env: prod
type: Opaque
stringData:
  DB_Host: cloudintel-db
  DB_Name: cloudintel_db
  DB_Password: smartvm
  DB_Port: "5432"
  DB_User: root

---

apiVersion: v1
kind: Secret
metadata:
  name: db-backup-secrets
  namespace: cloudintel
  labels:
    env: prod
type: Opaque
stringData:
  PGHOST: cloudintel-db
  PGDATABASE: cloudintel_db
  PGPASSWORD: smartvm
  PGPORT: "5432"
  PGUSER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: cloudintel
  labels:
    env: prod
type: Opaque
stringData:
  POSTGRES_PASSWORD: smartvm
  POSTGRES_USER: root
  POSTGRES_DB: cloudintel_db

---

apiVersion: v1
kind: Secret
metadata:
  name: cb-secrets
  namespace: cloudintel
  labels:
    env: prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://root:smartvm@cloudintel-db/cloudintel_db?encoding=utf8&pool=5&wait_timeout=5